apiVersion: v1
kind: Service
metadata:
  name: svc-google-cloud-deploy
  labels:
    name: svc-google-cloud-deploy
spec:
  type: LoadBalancer
  ports:
    - port: 80
      nodePort: 8080
  selector:
    name: google-cloud-deploy
